dist: bionic
language: python

env:
  - PYTEST_VERSION="pytest==3.8.0"  # min support version
  - PYTEST_VERSION="pytest==4.6.9"
  - PYTEST_VERSION="pytest==5.3.5"
  - PYTEST_VERSION="-U pytest"  # last version

python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install $PYTEST_VERSION
  - pip install pytest-cov==2.10.1
  - pip install responses==0.11.0
  - pip install -e .
script:
  - pytest ./tests
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  skip_existing: true
  distributions: bdist_wheel --universal
  on:
    tags: true
    repo: tolstislon/pytest-pytestrail
    python: "3.8"
    condition: $PYTEST_VERSION == "-U pytest"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always